name: chirpnet
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - cryptography=39.0.1
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - dbus=1.13.6
  - expat=2.4.8
  - ffmpeg=4.3
  - filelock=3.13.1
  - fontconfig=2.14.0
  - freetype=2.12.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.68.4
  - glib-tools=2.68.4
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - graphite2=1.3.13
  - gst-plugins-base=1.18.4
  - gstreamer=1.18.5
  - h5py=3.1.0
  - harfbuzz=2.9.1
  - hdf5=1.10.6
  - icu=68.2
  - idna=3.4
  - intel-openmp=2023.1.0
  - jasper=1.900.1
  - jinja2=3.1.3
  - jpeg=9e
  - keyutils=1.6.1
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.8.1.2
  - libcurand=10.3.4.107
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libevent=2.1.10
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.68.4
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libopencv=4.4.0
  - libpng=1.6.39
  - libpq=13.3
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuuid=2.32.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - ncurses=6.4
  - nettle=3.7.3
  - networkx=3.1
  - nspr=4.32
  - nss=3.69
  - numpy=1.24.3
  - numpy-base=1.24.3
  - opencv=4.4.0
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - pcre=8.45
  - pillow=10.0.1
  - pip=23.3.1
  - pixman=0.40.0
  - pthread-stubs=0.4
  - py-opencv=4.4.0
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.8.12
  - python_abi=3.8
  - pytorch=2.2.0
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - qt=5.12.9
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - sqlite=3.41.2
  - sympy=1.12
  - tbb=2021.8.0
  - tk=8.6.12
  - torchaudio=2.2.0
  - torchtriton=2.2.0
  - torchvision=0.17.0
  - tqdm=4.65.0
  - typing_extensions=4.9.0
  - urllib3=1.26.18
  - wheel=0.41.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.5
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - brevitas==0.10.3
    - contourpy==1.1.1
    - cycler==0.12.1
    - dependencies==2.0.1
    - fonttools==4.48.1
    - fsspec==2024.3.1
    - fvcore==0.1.5.post20221221
    - importlib-resources==6.1.1
    - iopath==0.1.10
    - joblib==1.3.2
    - kiwisolver==1.4.5
    - matplotlib==3.7.4
    - packaging==23.2
    - portalocker==2.10.1
    - pyparsing==3.1.1
    - python-dateutil==2.8.2
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - six==1.16.0
    - tabulate==0.9.0
    - termcolor==2.4.0
    - thop==0.1.1-2209072238
    - threadpoolctl==3.2.0
    - torchprofile==0.0.4
    - unfoldnd==0.2.2
    - yacs==0.1.8
    - zipp==3.17.0
